import type {
  ApplicationTask,
  AppSettings,
  CoverLetterDocument,
  Job,
  PipelineRun,
  StageEvent,
} from "../types";

export const createJob = (overrides: Partial<Job> = {}): Job => ({
  id: "job-1",
  source: "linkedin",
  sourceJobId: null,
  jobUrlDirect: null,
  datePosted: null,
  title: "Backend Engineer",
  employer: "Acme Labs",
  employerUrl: null,
  jobUrl: "https://example.com/job-1",
  applicationLink: "https://example.com/apply",
  disciplines: null,
  deadline: null,
  salary: null,
  location: "California",
  locationEvidence: null,
  locationMatch: null,
  degreeRequired: null,
  starting: null,
  jobDescription: "Job description content",
  status: "ready",
  outcome: null,
  closedAt: null,
  suitabilityCategory: "very_good_fit",
  suitabilityReason: "Strong fit",
  tailoredFields: {},
  tailoringMatched: null,
  tailoringSkipped: null,
  cvDocumentId: null,
  pdfPath: null,
  coverLetterDraft: "",
  coverLetterDocumentId: null,
  coverLetterFieldOverrides: {},
  coverLetterPdfPath: null,
  appliedDuplicateMatch: null,
  jobType: null,
  salarySource: null,
  salaryInterval: null,
  salaryMinAmount: null,
  salaryMaxAmount: null,
  salaryCurrency: null,
  isRemote: null,
  jobLevel: null,
  jobFunction: null,
  listingType: null,
  emails: null,
  companyIndustry: null,
  companyLogo: null,
  companyUrlDirect: null,
  companyAddresses: null,
  companyNumEmployees: null,
  companyRevenue: null,
  companyDescription: null,
  skills: null,
  experienceRange: null,
  companyRating: null,
  companyReviewsCount: null,
  vacancyCount: null,
  workFromHomeType: null,
  repostedAt: null,
  repostCount: 0,
  discoveredAt: "2025-01-01T00:00:00Z",
  processedAt: null,
  readyAt: "2025-01-01T00:00:00Z",
  appliedAt: null,
  createdAt: "2025-01-01T00:00:00Z",
  updatedAt: "2025-01-01T00:00:00Z",
  ...overrides,
});

export const createCoverLetterDocument = (
  overrides: Partial<CoverLetterDocument> = {},
): CoverLetterDocument => ({
  id: "cover-letter-1",
  name: "Default Cover Letter",
  flattenedTex: "",
  fields: [],
  templatedTex: "",
  defaultFieldValues: {},
  lastCompileStderr: null,
  compileAttempts: 0,
  extractionPrompt: "",
  createdAt: "2025-01-01T00:00:00Z",
  updatedAt: "2025-01-01T00:00:00Z",
  ...overrides,
});

export const createStageEvent = (
  overrides: Partial<StageEvent> = {},
): StageEvent => ({
  id: "event-1",
  applicationId: "job-1",
  title: "Moved to applied",
  groupId: null,
  fromStage: null,
  toStage: "applied",
  occurredAt: Date.now(),
  metadata: null,
  outcome: null,
  ...overrides,
});

export const createApplicationTask = (
  overrides: Partial<ApplicationTask> = {},
): ApplicationTask => ({
  id: "task-1",
  applicationId: "job-1",
  type: "todo",
  title: "Follow up",
  dueDate: null,
  isCompleted: false,
  notes: null,
  ...overrides,
});

export const createPipelineRun = (
  overrides: Partial<PipelineRun> = {},
): PipelineRun => ({
  id: "run-1",
  startedAt: "2025-01-01T00:00:00Z",
  completedAt: null,
  status: "running",
  jobsDiscovered: 0,
  jobsProcessed: 0,
  errorMessage: null,
  ...overrides,
});

export const createAppSettings = (
  overrides: Partial<AppSettings> = {},
): AppSettings => ({
  model: { value: "gpt-4o", default: "gpt-4o", override: null },
  modelScorer: { value: "gpt-4o", override: null },
  modelTailoring: { value: "gpt-4o", override: null },
  llmProvider: { value: "openai", default: "openai", override: null },
  llmBaseUrl: {
    value: "https://api.openai.com/v1",
    default: "https://api.openai.com/v1",
    override: null,
  },
  onboardingBasicAuthDecision: null,
  startupjobsMaxJobsPerTerm: { value: 50, default: 50, override: null },
  searchTerms: {
    value: ["Software Engineer"],
    default: ["Software Engineer"],
    override: null,
  },
  workplaceTypes: {
    value: ["remote", "hybrid", "onsite"],
    default: ["remote", "hybrid", "onsite"],
    override: null,
  },
  blockedCompanyKeywords: {
    value: [],
    default: [],
    override: null,
  },
  scoringInstructions: {
    value: "",
    default: "",
    override: null,
  },
  searchCities: {
    value: "",
    default: "",
    override: null,
  },
  locationSearchScope: {
    value: "selected_only",
    default: "selected_only",
    override: null,
  },
  locationMatchStrictness: {
    value: "exact_only",
    default: "exact_only",
    override: null,
  },
  jobspyResultsWanted: { value: 20, default: 20, override: null },
  jobspyCountryIndeed: {
    value: "",
    default: "",
    override: null,
  },
  showSponsorInfo: { value: true, default: true, override: null },
  renderMarkdownInJobDescriptions: {
    value: true,
    default: true,
    override: null,
  },
  chatStyleTone: {
    value: "professional",
    default: "professional",
    override: null,
  },
  chatStyleFormality: { value: "medium", default: "medium", override: null },
  chatStyleConstraints: { value: "", default: "", override: null },
  chatStyleDoNotUse: { value: "", default: "", override: null },
  chatStyleLanguageMode: {
    value: "manual",
    default: "manual",
    override: null,
  },
  chatStyleManualLanguage: {
    value: "english",
    default: "english",
    override: null,
  },
  chatStyleSummaryMaxWords: { value: null, default: null, override: null },
  chatStyleMaxKeywordsPerSkill: { value: null, default: null, override: null },
  llmApiKeyHint: null,
  basicAuthUser: null,
  basicAuthPassword: null,
  basicAuthPasswordHint: null,
  basicAuthActive: false,
  penalizeMissingSalary: { value: false, default: false, override: null },
  missingSalaryPenalty: { value: 10, default: 10, override: null },
  minSuitabilityCategory: {
    value: "good_fit",
    default: "good_fit",
    override: null,
  },
  autoSkipCategory: { value: null, default: null, override: null },
  autoTailoringEnabled: { value: false, default: false, override: null },
  enableJobScoring: { value: true, default: true, override: null },
  inboxStaleThresholdDays: { value: 7, default: 7, override: null },
  inboxAgeoutThresholdDays: { value: 14, default: 14, override: null },
  maxBriefChars: { value: 200_000, default: 200_000, override: null },
  maxJobDescriptionChars: { value: 100_000, default: 100_000, override: null },
  maxTailoredContentChars: {
    value: 100_000,
    default: 100_000,
    override: null,
  },
  maxCoverLetterChars: { value: 50_000, default: 50_000, override: null },
  maxFetchedJobHtmlChars: {
    value: 500_000,
    default: 500_000,
    override: null,
  },
  maxExtractionPromptChars: {
    value: 100_000,
    default: 100_000,
    override: null,
  },
  maxCvUploadBytes: {
    value: 50 * 1024 * 1024,
    default: 50 * 1024 * 1024,
    override: null,
  },
  maxCoverLetterUploadBytes: {
    value: 50 * 1024 * 1024,
    default: 50 * 1024 * 1024,
    override: null,
  },
  maxExpandedLatexBytes: {
    value: 50 * 1024 * 1024,
    default: 50 * 1024 * 1024,
    override: null,
  },
  ...overrides,
});
